modLoader = 'lowcodefml'
showAsResourcePack = false
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="satsu_iron_man_addon"
displayName="Satsu Iron man addon"
version="1.0.0"
logoFile = "logo.png"
logoBlur = false
description='''
This is a superior iron man addon
'''

[[dependencies.satsu_iron_man_addon]]
modId = "palladium"
mandatory = true
versionRange = ""
ordering = "NONE"
side = "BOTH"
